0 0 dataAuditErrors
1 0 non45Errors
2 0 offGridErrors
84 0 offGridShapeErrors: off grid polygon on layer Bondpad
86 0 offGridShapeErrors: off grid polygon on layer CapMetal
88 0 offGridShapeErrors: off grid polygon on layer Cont
90 0 offGridShapeErrors: off grid polygon on layer ESDdummy
92 0 offGridShapeErrors: off grid polygon on layer INDdummy
94 0 offGridShapeErrors: off grid polygon on layer M1Resdum
96 0 offGridShapeErrors: off grid polygon on layer M2Resdum
98 0 offGridShapeErrors: off grid polygon on layer M3Resdum
100 0 offGridShapeErrors: off grid polygon on layer M4Resdum
102 0 offGridShapeErrors: off grid polygon on layer M5Resdum
104 0 offGridShapeErrors: off grid polygon on layer M6Resdum
106 0 offGridShapeErrors: off grid polygon on layer M7Resdum
108 0 offGridShapeErrors: off grid polygon on layer M8Resdum
110 0 offGridShapeErrors: off grid polygon on layer M9Resdum
112 0 offGridShapeErrors: off grid polygon on layer M10Resdum
114 0 offGridShapeErrors: off grid polygon on layer M11Resdum
116 0 offGridShapeErrors: off grid polygon on layer Metal1
118 0 offGridShapeErrors: off grid polygon on layer Metal2
120 0 offGridShapeErrors: off grid polygon on layer Metal3
122 0 offGridShapeErrors: off grid polygon on layer Metal4
124 0 offGridShapeErrors: off grid polygon on layer Metal5
126 0 offGridShapeErrors: off grid polygon on layer Metal6
128 0 offGridShapeErrors: off grid polygon on layer Metal7
130 0 offGridShapeErrors: off grid polygon on layer Metal8
132 0 offGridShapeErrors: off grid polygon on layer Metal9
134 0 offGridShapeErrors: off grid polygon on layer Metal10
136 0 offGridShapeErrors: off grid polygon on layer Metal11
138 0 offGridShapeErrors: off grid polygon on layer NPNdummy
140 0 offGridShapeErrors: off grid polygon on layer Nburied
142 0 offGridShapeErrors: off grid polygon on layer Nhvt
144 0 offGridShapeErrors: off grid polygon on layer Nimp
146 0 offGridShapeErrors: off grid polygon on layer Nlvt
148 0 offGridShapeErrors: off grid polygon on layer Nwell
150 0 offGridShapeErrors: off grid polygon on layer Nzvt
152 0 offGridShapeErrors: off grid polygon on layer Oxide
154 0 offGridShapeErrors: off grid polygon on layer Oxide_thk
156 0 offGridShapeErrors: off grid polygon on layer PNPdummy
158 0 offGridShapeErrors: off grid polygon on layer Phvt
160 0 offGridShapeErrors: off grid polygon on layer Pimp
162 0 offGridShapeErrors: off grid polygon on layer Plvt
164 0 offGridShapeErrors: off grid polygon on layer Poly
166 0 offGridShapeErrors: off grid polygon on layer Psub
168 0 offGridShapeErrors: off grid polygon on layer ResWdum
170 0 offGridShapeErrors: off grid polygon on layer Resdum
172 0 offGridShapeErrors: off grid polygon on layer SiProt
174 0 offGridShapeErrors: off grid polygon on layer Via1
176 0 offGridShapeErrors: off grid polygon on layer Via2
178 0 offGridShapeErrors: off grid polygon on layer Via3
180 0 offGridShapeErrors: off grid polygon on layer Via4
182 0 offGridShapeErrors: off grid polygon on layer Via5
184 0 offGridShapeErrors: off grid polygon on layer Via6
186 0 offGridShapeErrors: off grid polygon on layer Via7
188 0 offGridShapeErrors: off grid polygon on layer Via8
190 0 offGridShapeErrors: off grid polygon on layer Via9
192 0 offGridShapeErrors: off grid polygon on layer Via10
194 0 non45 degree polygon on layer Bondpad
196 0 non45 degree polygon on layer CapMetal
198 0 non45 degree polygon on layer Cont
200 0 non45 degree polygon on layer ESDdummy
202 0 non45 degree polygon on layer INDdummy
204 0 non45 degree polygon on layer M1Resdum
206 0 non45 degree polygon on layer M2Resdum
208 0 non45 degree polygon on layer M3Resdum
210 0 non45 degree polygon on layer M4Resdum
212 0 non45 degree polygon on layer M5Resdum
214 0 non45 degree polygon on layer M6Resdum
216 0 non45 degree polygon on layer M7Resdum
218 0 non45 degree polygon on layer M8Resdum
220 0 non45 degree polygon on layer M9Resdum
222 0 non45 degree polygon on layer M10Resdum
224 0 non45 degree polygon on layer M11Resdum
226 0 non45 degree polygon on layer Metal1
228 0 non45 degree polygon on layer Metal2
230 0 non45 degree polygon on layer Metal3
232 0 non45 degree polygon on layer Metal4
234 0 non45 degree polygon on layer Metal5
236 0 non45 degree polygon on layer Metal6
238 0 non45 degree polygon on layer Metal7
240 0 non45 degree polygon on layer Metal8
242 0 non45 degree polygon on layer Metal9
244 0 non45 degree polygon on layer Metal10
246 0 non45 degree polygon on layer Metal11
248 0 non45 degree polygon on layer NPNdummy
250 0 non45 degree polygon on layer Nburied
252 0 non45 degree polygon on layer Nhvt
254 0 non45 degree polygon on layer Nimp
256 0 non45 degree polygon on layer Nlvt
258 0 non45 degree polygon on layer Nwell
260 0 non45 degree polygon on layer Nzvt
262 0 non45 degree polygon on layer Oxide
264 0 non45 degree polygon on layer Oxide_thk
266 0 non45 degree polygon on layer PNPdummy
268 0 non45 degree polygon on layer Phvt
270 0 non45 degree polygon on layer Pimp
272 0 non45 degree polygon on layer Plvt
274 0 non45 degree polygon on layer Poly
276 0 non45 degree polygon on layer Psub
278 0 non45 degree polygon on layer ResWdum
280 0 non45 degree polygon on layer Resdum
282 0 non45 degree polygon on layer SiProt
284 0 non45 degree polygon on layer Via1
286 0 non45 degree polygon on layer Via2
288 0 non45 degree polygon on layer Via3
290 0 non45 degree polygon on layer Via4
292 0 non45 degree polygon on layer Via5
294 0 non45 degree polygon on layer Via6
296 0 non45 degree polygon on layer Via7
298 0 non45 degree polygon on layer Via8
300 0 non45 degree polygon on layer Via9
302 0 non45 degree polygon on layer Via10
303 0 acute angle on layer Bondpad
304 0 acute angle on layer ESDdummy
305 0 acute angle on layer INDdummy
306 0 acute angle on layer M1Resdum
307 0 acute angle on layer M2Resdum
308 0 acute angle on layer M3Resdum
309 0 acute angle on layer M4Resdum
310 0 acute angle on layer M5Resdum
311 0 acute angle on layer M6Resdum
312 0 acute angle on layer M7Resdum
313 0 acute angle on layer M8Resdum
314 0 acute angle on layer M9Resdum
315 0 acute angle on layer M10Resdum
316 0 acute angle on layer M11Resdum
317 0 acute angle on layer NPNdummy
318 0 acute angle on layer PNPdummy
319 0 acute angle on layer Psub
320 0 acute angle on layer ResWdum
321 0 acute angle on layer Resdum
360 0 NZVT.X.4: Only one Oxide region may be in an Nzvt region
503 0 BONDPAD.L.1: Bondpad length must be >= 68.0 um
507 0 NBL.X.1: Nburied must have an Nwell isolation ring
568 0 NZVT.O.1: Minimum and maximum Nzvt to Active Area overlap == 0.16 um
781 0 VIAk.X.3_VIAk.X.4: Metal1 through Metal6 stack must have two or more stacked Vias at all levels
786 0 VIAk.X.3_VIAk.X.4: Metal2 through Metal7 stack must have two or more stacked Vias at all levels
791 0 VIAk.X.3_VIAk.X.4: Metal3 through Metal8 stack must have two or more stacked Vias at all levels
796 0 VIAk.X.3_VIAk.X.4: Metal4 through Metal9 stack must have two or more stacked Vias at all levels
1086 0 POLY.SE.3: Maximum Poly segment length (width < 0.14) between two contacts >= 12.0 um
1095 0 VIA1.E.3: At least 2 Via1 must be used to join Metal1 and Metal2 when they are within 3.0um of a metal plate (Metal1/Metal2) when the metal plate size is has width > 1.5 and length > 1.5
1104 0 VIA2.E.3: At least 2 Via2 must be used to join Metal2 and Metal3 when they are within 3.0um of a metal plate (Metal2/Metal3) when the metal plate size is has width > 1.5 and length > 1.5
1113 0 VIA3.E.3: At least 2 Via3 must be used to join Metal3 and Metal4 when they are within 3.0um of a metal plate (Metal3/Metal4) when the metal plate size is has width > 1.5 and length > 1.5
1122 0 VIA4.E.3: At least 2 Via4 must be used to join Metal4 and Metal5 when they are within 3.0um of a metal plate (Metal4/Metal5) when the metal plate size is has width > 1.5 and length > 1.5
1131 0 VIA5.E.3: At least 2 Via5 must be used to join Metal5 and Metal6 when they are within 3.0um of a metal plate (Metal5/Metal6) when the metal plate size is has width > 1.5 and length > 1.5
1140 0 VIA6.E.3: At least 2 Via6 must be used to join Metal6 and Metal7 when they are within 3.0um of a metal plate (Metal6/Metal7) when the metal plate size is has width > 1.5 and length > 1.5
1149 0 VIA7.E.3: At least 2 Via7 must be used to join Metal7 and Metal8 when they are within 3.0um of a metal plate (Metal7/Metal8) when the metal plate size is has width > 1.5 and length > 1.5
1158 0 VIA8.E.3: At least 2 Via8 must be used to join Metal8 and Metal9 when they are within 3.0um of a metal plate (Metal8/Metal9) when the metal plate size is has width > 1.5 and length > 1.5
1170 0 BONDPAD.SP.5: Bondpad Metal1 slot to Bondpad Metal1 slot spacing must be == 1.50
1174 0 BONDPAD.W.4: Bondpad Metal1 slot width must be == 1.00
1185 0 BONDPAD.R.1: Minimum Bondpad Via1 inside Metal1 to Metal2 crossing must be >= 16.0
1190 0 BONDPAD.SP.5: Bondpad Metal2 slot to Bondpad Metal2 slot spacing must be == 1.50
1194 0 BONDPAD.W.4: Bondpad Metal2 slot width must be == 1.00
1205 0 BONDPAD.R.1: Minimum Bondpad Via2 inside Metal2 to Metal3 crossing must be >= 16.0
1210 0 BONDPAD.SP.5: Bondpad Metal3 slot to Bondpad Metal3 slot spacing must be == 1.50
1214 0 BONDPAD.W.4: Bondpad Metal3 slot width must be == 1.00
1225 0 BONDPAD.R.1: Minimum Bondpad Via3 inside Metal3 to Metal4 crossing must be >= 16.0
1230 0 BONDPAD.SP.5: Bondpad Metal4 slot to Bondpad Metal4 slot spacing must be == 1.50
1234 0 BONDPAD.W.4: Bondpad Metal4 slot width must be == 1.00
1245 0 BONDPAD.R.1: Minimum Bondpad Via4 inside Metal4 to Metal5 crossing must be >= 16.0
1250 0 BONDPAD.SP.5: Bondpad Metal5 slot to Bondpad Metal5 slot spacing must be == 1.50
1254 0 BONDPAD.W.4: Bondpad Metal5 slot width must be == 1.00
1265 0 BONDPAD.R.1: Minimum Bondpad Via5 inside Metal5 to Metal6 crossing must be >= 16.0
1270 0 BONDPAD.SP.5: Bondpad Metal6 slot to Bondpad Metal6 slot spacing must be == 1.50
1274 0 BONDPAD.W.4: Bondpad Metal6 slot width must be == 1.00
1285 0 BONDPAD.R.1: Minimum Bondpad Via6 inside Metal6 to Metal7 crossing must be >= 16.0
1290 0 BONDPAD.SP.5: Bondpad Metal7 slot to Bondpad Metal7 slot spacing must be == 1.50
1294 0 BONDPAD.W.4: Bondpad Metal7 slot width must be == 1.00
1305 0 BONDPAD.R.1: Minimum Bondpad Via7 inside Metal7 to Metal8 crossing must be >= 16.0
1310 0 BONDPAD.SP.5: Bondpad Metal8 slot to Bondpad Metal8 slot spacing must be == 1.50
1314 0 BONDPAD.W.4: Bondpad Metal8 slot width must be == 1.00
1325 0 BONDPAD.R.1: Minimum Bondpad Via8 inside Metal8 to Metal9 crossing must be >= 16.0
1330 0 BONDPAD.SP.5: Bondpad Metal9 slot to Bondpad Metal9 slot spacing must be == 1.50
1334 0 BONDPAD.W.4: Bondpad Metal9 slot width must be == 1.00
1345 0 BONDPAD.R.2: Minimum Bondpad Via9 inside Metal9 to Metal10 crossing must be >= 4.0
1350 0 BONDPAD.SP.5: Bondpad Metal10 slot to Bondpad Metal10 slot spacing must be == 1.50
1354 0 BONDPAD.W.4: Bondpad Metal10 slot width must be == 1.00
1359 0 BONDPAD.R.2: Minimum Bondpad Via10 inside Metal10 to Metal11 crossing must be >= 4.0
1738 0 OXIDE.L.1_OXIDE.L.2: Maximum Oxide length between two contacts (when the Oxide width is <= 0.18um) must be <= 12.0um and Maximum Oxide length between one contact and the end of the Oxide line (when the Oxide width is <= 0.18um) must be <= 6.0um
1766 0 BONDPAD.W.5: Bondpad Metal1 outside Metal1 ring width must be == 5.00
1794 0 BONDPAD.W.5: Bondpad Metal2 outside Metal2 ring width must be == 5.00
1822 0 BONDPAD.W.5: Bondpad Metal3 outside Metal3 ring width must be == 5.00
1850 0 BONDPAD.W.5: Bondpad Metal4 outside Metal4 ring width must be == 5.00
1878 0 BONDPAD.W.5: Bondpad Metal5 outside Metal5 ring width must be == 5.00
1906 0 BONDPAD.W.5: Bondpad Metal6 outside Metal6 ring width must be == 5.00
1934 0 BONDPAD.W.5: Bondpad Metal7 outside Metal7 ring width must be == 5.00
1962 0 BONDPAD.W.5: Bondpad Metal8 outside Metal8 ring width must be == 5.00
1990 0 BONDPAD.W.5: Bondpad Metal9 outside Metal9 ring width must be == 5.00
2018 0 BONDPAD.W.5: Bondpad Metal10 outside Metal10 ring width must be == 5.00
2037 0 VIA1.X.2: Metal1 must connect to Metal2 with >= 4 Via1 spaced < 0.30 um or >= 9 Via1 spaced < 0.60 um
2056 0 VIA2.X.2: Metal2 must connect to Metal3 with >= 4 Via2 spaced < 0.30 um or >= 9 Via2 spaced < 0.60 um
2075 0 VIA3.X.2: Metal3 must connect to Metal4 with >= 4 Via3 spaced < 0.30 um or >= 9 Via3 spaced < 0.60 um
2094 0 VIA4.X.2: Metal4 must connect to Metal5 with >= 4 Via4 spaced < 0.30 um or >= 9 Via4 spaced < 0.60 um
2113 0 VIA5.X.2: Metal5 must connect to Metal6 with >= 4 Via5 spaced < 0.30 um or >= 9 Via5 spaced < 0.60 um
2132 0 VIA6.X.2: Metal6 must connect to Metal7 with >= 4 Via6 spaced < 0.30 um or >= 9 Via6 spaced < 0.60 um
2151 0 VIA7.X.2: Metal7 must connect to Metal8 with >= 4 Via7 spaced < 0.30 um or >= 9 Via7 spaced < 0.60 um
2170 0 VIA8.X.2: Metal8 must connect to Metal9 with >= 4 Via8 spaced < 0.30 um or >= 9 Via8 spaced < 0.60 um
2190 0 VIA1.X.1: Metal1 must connect to Metal2 with >= 2 Via1 spaced < 0.30 um or >= 4 Via1 spaced < 0.60 um
2210 0 VIA2.X.1: Metal2 must connect to Metal3 with >= 2 Via2 spaced < 0.30 um or >= 4 Via2 spaced < 0.60 um
2230 0 VIA3.X.1: Metal3 must connect to Metal4 with >= 2 Via3 spaced < 0.30 um or >= 4 Via3 spaced < 0.60 um
2250 0 VIA4.X.1: Metal4 must connect to Metal5 with >= 2 Via4 spaced < 0.30 um or >= 4 Via4 spaced < 0.60 um
2270 0 VIA5.X.1: Metal5 must connect to Metal6 with >= 2 Via5 spaced < 0.30 um or >= 4 Via5 spaced < 0.60 um
2290 0 VIA6.X.1: Metal6 must connect to Metal7 with >= 2 Via6 spaced < 0.30 um or >= 4 Via6 spaced < 0.60 um
2310 0 VIA7.X.1: Metal7 must connect to Metal8 with >= 2 Via7 spaced < 0.30 um or >= 4 Via7 spaced < 0.60 um
2330 0 VIA8.X.1: Metal8 must connect to Metal9 with >= 2 Via8 spaced < 0.30 um or >= 4 Via8 spaced < 0.60 um
2336 0 BONDPAD.B.1A: Bondpad Metal1 must have bevelled corners
2342 0 BONDPAD.B.1A: Bondpad Metal2 must have bevelled corners
2348 0 BONDPAD.B.1A: Bondpad Metal3 must have bevelled corners
2354 0 BONDPAD.B.1A: Bondpad Metal4 must have bevelled corners
2360 0 BONDPAD.B.1A: Bondpad Metal5 must have bevelled corners
2366 0 BONDPAD.B.1A: Bondpad Metal6 must have bevelled corners
2372 0 BONDPAD.B.1A: Bondpad Metal7 must have bevelled corners
2378 0 BONDPAD.B.1A: Bondpad Metal8 must have bevelled corners
2384 0 BONDPAD.B.1A: Bondpad Metal9 must have bevelled corners
2390 0 BONDPAD.B.1A: Bondpad Metal10 must have bevelled corners
2396 0 BONDPAD.B.1A: Bondpad Metal11 must have bevelled corners
2398 0 ptap_StampErrorFloat
2399 0 ptap_StampErrorMult
2400 0 ptap_StampErrorConnect
2405 0 psubstrate_StampErrorFloat
2406 0 psubstrate_StampErrorMult
2407 0 psubstrate_StampErrorConnect
2412 0 ntap_StampErrorFloat
2413 0 ntap_StampErrorMult
2414 0 ntap_StampErrorConnect
2419 0 nwell_conn_StampErrorFloat
2420 0 nwell_conn_StampErrorMult
2421 0 nwell_conn_StampErrorConnect
2426 0 nb_tap_StampErrorFloat
2427 0 nb_tap_StampErrorMult
2428 0 nb_tap_StampErrorConnect
2433 0 Nburied_StampErrorFloat
2434 0 Nburied_StampErrorMult
2435 0 Nburied_StampErrorConnect
2473 0 NBL.W.1: Minimum Nburied Width >= 0.8 um
2475 0 NBL.E.1: Minimum Nburied to Nwell enclosure >= 0.2 um
2477 0 NBL.E.1: Minimum Nburied to Nwell enclosure >= 0.2 um
2479 0 NBL.SP.1: Minimum Nburied to Nburied spacing >= 2.0 um
2481 0 NBL.SE.1: Minimum Nburied to non-related Nwell spacing >= 2.2 um
2482 0 NBL.SE.1: Minimum Nburied to non-related Nwell spacing >= 2.2 um
2485 0 NBL.SE.2: Minimum Nburied to non-related Oxide spacing >= 1.2 um
2486 0 NBL.SE.2: Minimum Nburied to non-related Oxide spacing >= 1.2 um
2491 0 NBL.SE.3: Minimum Nwell ring (on Nburied) to P+ Active spacing >= 0.09 um
2493 0 NBL.SE.3: Minimum Nwell ring (on Nburied) to P+ Active spacing >= 0.09 um
2497 0 NBL.SE.4: Minimum Nwell ring (on Nburied) to N+ Active spacing >= 0.09 um
2499 0 NBL.SE.4: Minimum Nwell ring (on Nburied) to N+ Active spacing >= 0.09 um
2501 0 NW.SP.1: Minimum Nwell spacing to Nwell (same potential) >= 0.3 um
2503 0 NW.SP.1: Minimum Nwell spacing to Nwell (same potential) >= 0.3 um
2506 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2507 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2509 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2510 0 NW.W.1: Minimum Nwell Width >= 0.3 um
2512 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2515 0 NW.SE.2: Minimum Nwell spacing to P+ Active Area >= 0.16 um
2516 0 NW.SE.2: Minimum Nwell spacing to P+ Active Area >= 0.16 um
2520 0 NW.SE.1: Minimum Nwell spacing to N+ Active Area >= 0.16 um
2521 0 NW.SE.1: Minimum Nwell spacing to N+ Active Area >= 0.16 um
2526 0 NW.SE.3: Minimum Nwell spacing to N+ 1.8V Active Area >= 0.24 um
2527 0 NW.SE.3: Minimum Nwell spacing to N+ 1.8V Active Area >= 0.24 um
2532 0 NW.SE.4: Minimum Nwell spacing to P+ 1.8V Active Area >= 0.24 um
2533 0 NW.SE.4: Minimum Nwell spacing to P+ 1.8V Active Area >= 0.24 um
2537 0 NW.E.1: Minimum Nwell enclosure of N+ Active Area >= 0.06 um
2539 0 NW.E.1: Minimum Nwell enclosure of N+ Active Area >= 0.06 um
2540 0 NW.E.2: Minimum Nwell enclosure of P+ Active Area >= 0.06 um
2542 0 NW.E.2: Minimum Nwell enclosure of P+ Active Area >= 0.06 um
2543 0 NW.E.3: Minimum Nwell enclosure of N+ 1.8V Active Area >= 0.24 um
2545 0 NW.E.3: Minimum Nwell enclosure of N+ 1.8V Active Area >= 0.24 um
2546 0 NW.E.4: Minimum Nwell enclosure of P+ 1.8V Active Area >= 0.24 um
2548 0 NW.E.4: Minimum Nwell enclosure of P+ 1.8V Active Area >= 0.24 um
2549 0 NW.A.1: Minimum Nwell area >= 0.18 um
2550 0 NW.EA.1: Minimum Nwell enclosed area >= 0.18 um
2551 0 NWR.SE.1: Minimum Resist Protect Oxide to Nwell spacing >= 0.16 um
2553 0 NWR.E.1: Minimum Active Area to Nwell (in resistor) enclosure >= 0.6 um
2555 0 NWR.E.2: Minimum salicided Nwell to Contact enclosure >= 0.16 um
2557 0 NWR.E.2: Minimum salicided Nwell to Contact enclosure >= 0.16 um
2558 0 NWR.X.1: Thick Oxide is NOT allowed over Nwell resistor
2563 0 NWR.O.1: Minimum N+ Implant to Resist Protect Oxide overlap >= 0.22 um
2564 0 OXIDE.W.1: Minimum Active Area width >= 0.05 um
2569 0 OXIDE.W.2.1.1: Minimum 1.1V N-channel gate width >= 0.12 um
2573 0 OXIDE.W.2.1.2: Minimum 1.8V N-channel gate width >= 0.32 um
2578 0 OXIDE.W.2.2.1: Minimum 1.1V P-channel gate width >= 0.12 um
2582 0 OXIDE.W.2.2.2: Minimum 1.8V P-channel gate width >= 0.32 um
2584 0 OXIDE.W.3: Minimum Active Area bent 45 degress width >= 0.06 um
2586 0 OXIDE.SP.1: Minimum N+ Active Area to N+ Active Area spacing >= 0.08 um
2588 0 OXIDE.SP.2: Minimum P+ Active Area to P+ Active Area spacing >= 0.08 um
2593 0 OXIDE.SP.3: Minimum N+ Active Area to P+ Active Area spacing >= 0.1 um
2594 0 OXIDE.SE.1: Minimum Active Area to Thick Active Area spacing >= 0.18 um
2595 0 OXIDE.SP.4: Minimum Active Area bent 45 degress to Active Area spacing >= 0.1 um
2596 0 OXIDE.A.1: Minimum area for Active Area >= 0.035 um
2600 0 OXIDE.EA.1: Minimum Active Area enclosed area >= 0.04 um
2604 0 OXIDE.X.1: Oxide must be covered by N+ Implant or Nzvt or Salicide Block
2607 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2608 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2611 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2612 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2614 0 OXIDER.E.1: Minimum Salicide Block to Active Resistor enclosure >= 0.12 um
2616 0 OXIDER.X.1: Oxide resistors must have N+ or P+ Implant
2617 0 OXIDETHK.W.1: Minimum Thick Active Area width >= 0.35 um
2619 0 OXIDETHK.SP.1: Minimum Thick Active Area to Thick Active Area spacing >= 0.16 um
2621 0 OXIDETHK.SP.2: Minimum Thick Active Area bent 45 degrees to Thick Active Area spacing >= 0.32 um
2623 0 OXIDETHK.SE.1: Minimum N+ 1.8V Active Area to 1.8V N+ Active Area spacing >= 0.1 um
2625 0 OXIDETHK.SE.2: Minimum P+ 1.8V Active Area to 1.8V P+ Active Area spacing >= 0.1 um
2626 0 OXIDETHK.SE.3: Minimum N+ 1.8V Active Area to 1.8V P+ Active Area spacing >= 0.12 um
2628 0 OXIDETHK.E.1: Minimum Thick Active Area to Active Area enclosure >= 0.16 um
2635 0 OXIDETHK.SE.5: Minimum Thick Active Area to 1.1V Poly gate spacing >= 0.18 um
2636 0 OXIDETHK.SE.5: Minimum Thick Active Area to 1.1V Poly gate spacing >= 0.18 um
2638 0 OXIDETHK.E.2: Minimum Thick Active Area to Thick Poly gate enclosure >= 0.18 um
2639 0 NHVT.W.1: Minimum Nhvt width >= 0.12
2641 0 NHVT.SP.1: Minimum Nhvt spacing >= 0.12
2642 0 NHVT.X.2: Nhvt is NOT allowed on Nwell
2643 0 NHVT.X.3: Nhvt is NOT allowed on P+ Oxide
2644 0 NHVT.X.4: Nhvt is NOT allowed on Nzvt
2645 0 PHVT.W.1: Minimum Phvt width >= 0.12
2647 0 PHVT.SP.1: Minimum Phvt spacing >= 0.12
2648 0 PHVT.X.2: Phvt is NOT allowed outside Nwell
2649 0 PHVT.X.3: Phvt is NOT allowed on N+ Oxide
2650 0 PHVT.X.4: Phvt is NOT allowed on Nzvt
2651 0 NLVT.W.1: Minimum Nlvt width >= 0.12
2653 0 NLVT.SP.1: Minimum Nlvt spacing >= 0.12
2654 0 NLVT.X.2: Nlvt is NOT allowed on Nwell
2655 0 NLVT.X.3: Nlvt is NOT allowed on P+ Oxide
2656 0 NLVT.X.4: Nlvt is NOT allowed on Nzvt
2657 0 PLVT.W.1: Minimum Plvt width >= 0.12
2659 0 PLVT.SP.1: Minimum Plvt spacing >= 0.12
2660 0 PLVT.X.2: Plvt is NOT allowed outside Nwell
2661 0 PLVT.X.3: Plvt is NOT allowed on N+ Oxide
2662 0 PLVT.X.4: Plvt is NOT allowed on Nzvt
2663 0 NZVT.W.1: Minimum Nzvt width >= 0.35 um
2665 0 NZVT.SP.1: Minimum Nzvt to Nzvt spacing >= 0.3 um
2668 0 NZVT.SE.1: Minimum Nzvt to Active spacing >= 0.18 um
2669 0 NZVT.SE.1: Minimum Nzvt to Active spacing >= 0.18 um
2670 0 NZVT.SE.2: Minimum Nzvt to Nwell spacing >= 0.6 um
2671 0 NZVT.SE.2: Minimum Nzvt to Nwell spacing >= 0.6 um
2674 0 NZVT.E.1: Minimum N+ Poly gate end cap to Native Active Area enclosure >= 0.1 um
2677 0 NZVT.L.1: Minimum Native device Poly gate length >= 0.30 um
2681 0 NZVT.W.2: Minimum Native device Poly gate width >= 0.50 um
2683 0 NZVT.X.3: P+ Oxide is NOT allowed in Nzvt
2686 0 POLY.W.1: Minimum 1.1V N-channel gate length >= 0.045 um
2689 0 POLY.W.2: Minimum 1.1V P-channel gate length >= 0.045 um
2693 0 POLY.W.3: Minimum 1.8V N-channel gate length >= 0.15 um
2698 0 POLY.W.4: Minimum 1.8V P-channel gate length >= 0.15 um
2701 0 POLY.W.5: Minimum Poly interconnect width >= 0.045 um
2705 0 POLY.SP.1: Minimum Poly resistor space >= 0.3 um
2707 0 POLY.SP.2: Minimum Poly gate space  >= 0.06 um
2709 0 POLY.SP.3: Minimum Poly interconnect space >= 0.06 um
2713 0 POLY.SP.4: Minimum gate space in thick active >= 0.20 um
2716 0 POLY.E.1: Minimum N-channel gate extension beyond Active Area >= 0.1 um
2718 0 POLY.E.1: Minimum N-channel gate extension beyond Active Area >= 0.1 um
2721 0 POLY.E.2: Minimum P-channel gate extension beyond Active Area >= 0.1 um
2723 0 POLY.E.2: Minimum P-channel gate extension beyond Active Area >= 0.1 um
2724 0 POLY.SE.1_POLY.SE.2: Minimum Poly interconnect to related Active Area space >= 0.05 um
2726 0 POLY.E.3: Minimum Active Area (source/drain) to gate enclosure >= 0.1 um
2728 0 POLY.W.6: Minimum bent Poly width >= 0.1 um
2730 0 POLY.SP.5: Minimum bent Poly space >= 0.1 um
2731 0 POLY.X.1: Poly gate cannot have bends
2732 0 POLY.X.2: Poly resistor cannot have bends
4144 0 POLY.LN.1  Maximum Poly length [Poly width is <= 0.16 um] between two contacts as well as between one contact and the Poly line end <= 20um  
4145 0 POLY.A.1: Minimum area for Poly interconnect >= 0.02 um
4149 0 POLY.EA.1: Minimum enclosed area for Poly interconnect >= 0.05 um
4151 0 POLYR.E.1: Minimum Salicide Block to Poly resistor enclosure >= 0.14 um
4153 0 POLYR.E.2: Minimum N+ Implant to Poly used in resistor enclosure >= 0.07 um
4155 0 POLYR.E.2: Minimum N+ Implant to Poly used in resistor enclosure >= 0.07 um
4157 0 POLYR.E.3: Minimum P+ Implant to Poly used in resistor enclosure >= 0.07 um
4159 0 POLYR.E.3: Minimum P+ Implant to Poly used in resistor enclosure >= 0.07 um
4161 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4162 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4163 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4164 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4166 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4167 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4168 0 POLYR.X.1: Poly resistors must have N+ or P+ Implant
4169 0 NIMP.W.1: Minimum N+ Implant width >= 0.12 um
4171 0 NIMP.SP.1: Minimum N+ Implant space >= 0.12 um
4174 0 NIMP.E.1: Minimum N+ Implant to Active Area enclosure >= 0.07 um
4175 0 NIMP.O.1: Minimum N+ Implant to Active Area overlap >= 0.08 um
4183 0 NIMP.SE.1: Minimum N+ Implant to P+ Active Area (inside Nwell) spacing >= 0.08 um
4184 0 NIMP.SE.1: Minimum N+ Implant to P+ Active Area (inside Nwell) spacing >= 0.08 um
4187 0 NIMP.E.2: Minimum N+ Implant to Active Area (Nwell tie) enclosure >= 0.01 um
4191 0 NIMP.E.3: Minimum N+ Implant to gate side enclosure >= 0.1 um
4197 0 NIMP.E.4: Minimum N+ Implant to gate (endcap) enclosure >= 0.1 um
4199 0 NIMP.E.4: Minimum N+ Implant to gate (endcap) enclosure >= 0.1 um
4208 0 NIMP.SE.2: Minimum N+ Implant to P+ Active Area (substrate tie) spacing >= 0.02 um
4209 0 NIMP.SE.2: Minimum N+ Implant to P+ Active Area (substrate tie) spacing >= 0.02 um
4210 0 NIMP.A.1: Minimum area for N+ Implant >= 0.018 um
4214 0 NIMP.EA.1: Minimum N+ Implant ring enclosed area  >= 0.04 um
4217 0 NIMP.SE.3: Minimum N+ Implant to P+ gate side (butted Implant) spacing >= 0.1 um
4218 0 NIMP.SE.3: Minimum N+ Implant to P+ gate side (butted Implant) spacing >= 0.1 um
4219 0 NIMP.X.1: Nimp is NOT allowed over Pimp
4220 0 PIMP.W.1: Minimum P+ Implant width >= 0.12 um
4222 0 PIMP.SP.1: Minimum P+ Implant space >= 0.12 um
4224 0 PIMP.E.1: Minimum P+ Implant to Active Area enclosure >= 0.07 um
4225 0 PIMP.O.1: Minimum P+ Implant to Active Area overlap >= 0.08 um
4233 0 PIMP.SE.1: Minimum P+ Implant to N+ Active Area (outside Nwell) spacing >= 0.08 um
4234 0 PIMP.SE.1: Minimum P+ Implant to N+ Active Area (outside Nwell) spacing >= 0.08 um
4236 0 PIMP.E.2: Minimum P+ Implant to Active Area (substrate tie) enclosure >= 0.01 um
4240 0 PIMP.E.3: Minimum P+ Implant to gate side enclosure >= 0.1 um
4243 0 PIMP.E.4: Minimum P+ Implant to gate (endcap) enclosure >= 0.1 um
4245 0 PIMP.E.4: Minimum P+ Implant to gate (endcap) enclosure >= 0.1 um
4254 0 PIMP.SE.2: Minimum P+ Implant to N+ Active Area (Nwell tie) spacing >= 0.02 um
4255 0 PIMP.SE.2: Minimum P+ Implant to N+ Active Area (Nwell tie) spacing >= 0.02 um
4256 0 PIMP.A.1: Minimum area for P+ Implant >= 0.018 um
4260 0 PIMP.EA.1: Minimum P+ Implant ring enclosed area  >= 0.04 um
4263 0 PIMP.SE.3: Minimum P+ Implant to N+ gate side (butted Implant) spacing >= 0.1 um
4264 0 PIMP.SE.3: Minimum P+ Implant to N+ gate side (butted Implant) spacing >= 0.1 um
4266 0 CONT.W.1: Maximum and minimum Contact width/length == 0.06 um
4268 0 CONT.SP.1: Minimum Contact to Contact spacing >= 0.06 um
4270 0 CONT.SP.2: Space to three adjacent Contacts ( < 0.10um apart) >= 0.08 um
4273 0 CONT.SE.1: Minimum Contact on Active Area to gate spacing >= 0.05 um
4274 0 CONT.SE.1: Minimum Contact on Active Area to gate spacing >= 0.05 um
4278 0 CONT.SE.2: Minimum Contact on 1.8V Active Area to gate spacing >= 0.06 um
4279 0 CONT.SE.2: Minimum Contact on 1.8V Active Area to gate spacing >= 0.06 um
4281 0 CONT.SE.3: Minimum gate Contact on Active Area spacing >= 0.06 um
4282 0 CONT.SE.3: Minimum gate Contact on Active Area spacing >= 0.06 um
4287 0 CONT.SE.4: Minimum 1.8V gate Contact on Active Area spacing >= 0.07 um
4288 0 CONT.SE.4: Minimum 1.8V gate Contact on Active Area spacing >= 0.07 um
4290 0 CONT.E.1: Minimum Active Area to Contact enclosure >= 0.03 um
4292 0 CONT.E.1: Minimum Active Area to Contact enclosure >= 0.03 um
4294 0 CONT.E.2: Minimum Poly to Contact enclosure >= 0.02 um
4296 0 CONT.E.2: Minimum Poly to Contact enclosure >= 0.02 um
4299 0 CONT.E.3: Minimum Poly to Contact enclosure on at least two opposite sides >= 0.03 um
4302 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4304 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4307 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4309 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4310 0 CONT.X.1: Cont on gate is NOT allowed
4313 0 CONT.X.2: Nimp edge is NOT allowed on Oxide Cont
4316 0 CONT.X.2: Pimp edge is NOT allowed on Oxide Cont
4317 0 CONT.X.3: CONT must be covered by Oxide or Poly
4318 0 SIPROT.W.1: Minimum Salicide Block width >= 0.22 um
4320 0 SIPROT.SP.1: Minimum Salicide Block space >= 0.22 um
4323 0 SIPROT.SE.1: Minimum Salicide Block to Contact spacing >= 0.12 um
4324 0 SIPROT.SE.1: Minimum Salicide Block to Contact spacing >= 0.12 um
4325 0 SIPROT.SE.2: Minimum Salicide Block to unrelated Active Area spacing >= 0.12 um
4329 0 SIPROT.SE.3: Minimum Salicide Block to gate spacing >= 0.22 um
4330 0 SIPROT.SE.3: Minimum Salicide Block to gate spacing >= 0.22 um
4332 0 SIPROT.E.2: Minimum Active Area to Salicide Block enclosure >= 0.12 um
4336 0 SIPROT.E.1: Minimum Salicide Block to Active Area enclosure >= 0.12 um
4338 0 SIPROT.E.3: Minimum Salicide Block to Poly (on field) enclosure >= 0.14 um
4339 0 SIPROT.A.1: Minimum Salicide Block area >= 0.6 um
4340 0 SIPROT.SE.4: Minimum Salicide Block to Poly (on field) spacing >= 0.18 um
4344 0 SIPROT.EA.1: Minimum Salicide Block enclosed area >= 0.6 um
4345 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
4347 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
4351 0 METAL2.E.2: Metal2 to Via1 enclosure on opposite sides must be >= 0.03 um
4352 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
4354 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
4358 0 METAL3.E.2: Metal3 to Via2 enclosure on opposite sides must be >= 0.03 um
4359 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
4361 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
4365 0 METAL4.E.2: Metal4 to Via3 enclosure on opposite sides must be >= 0.03 um
4366 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
4368 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
4372 0 METAL5.E.2: Metal5 to Via4 enclosure on opposite sides must be >= 0.03 um
4373 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
4375 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
4379 0 METAL6.E.2: Metal6 to Via5 enclosure on opposite sides must be >= 0.03 um
4380 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
4382 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
4386 0 METAL7.E.2: Metal7 to Via6 enclosure on opposite sides must be >= 0.03 um
4387 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.005 um
4389 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.005 um
4393 0 METAL8.E.2: Metal8 to Via7 enclosure on opposite sides must be >= 0.03 um
4394 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.005 um
4396 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.005 um
4400 0 METAL9.E.2: Metal9 to Via8 enclosure on opposite sides must be >= 0.03 um
4401 0 METAL10.E.1: Metal10 to Via9 enclosure must be >= 0.03 um
4403 0 METAL10.E.1: Metal10 to Via9 enclosure must be >= 0.03 um
4407 0 METAL10.E.2: Metal10 to Via9 enclosure on opposite sides must be >= 0.05 um
4408 0 METAL11.E.1: Metal11 to Via10 enclosure must be >= 0.03 um
4410 0 METAL11.E.1: Metal11 to Via10 enclosure must be >= 0.03 um
4414 0 METAL11.E.2: Metal11 to Via10 enclosure on opposite sides must be >= 0.05 um
4415 0 METAL1.E.1: 0.00 >= 0.00 um
4419 0 METAL1.E.2: 0.03 >= 0.03 um
4420 0 METAL1.W.1: Metal1 width must be >= 0.06 um
4421 0 METAL2.W.1: Metal2 width must be >= 0.08 um
4422 0 METAL3.W.1: Metal3 width must be >= 0.08 um
4423 0 METAL4.W.1: Metal4 width must be >= 0.08 um
4424 0 METAL5.W.1: Metal5 width must be >= 0.08 um
4425 0 METAL6.W.1: Metal6 width must be >= 0.08 um
4426 0 METAL7.W.1: Metal7 width must be >= 0.08 um
4427 0 METAL8.W.1: Metal8 width must be >= 0.08 um
4428 0 METAL9.W.1: Metal9 width must be >= 0.08 um
4429 0 METAL10.W.1: Metal10 width must be >= 0.22 um
4430 0 METAL11.W.1: Metal11 width must be >= 0.22 um
4434 0 METAL1.W.2: Metal1 width must be <= 6.0 um
4438 0 METAL2.W.2: Metal2 width must be <= 6.0 um
4442 0 METAL3.W.2: Metal3 width must be <= 6.0 um
4446 0 METAL4.W.2: Metal4 width must be <= 6.0 um
4450 0 METAL5.W.2: Metal5 width must be <= 6.0 um
4454 0 METAL6.W.2: Metal6 width must be <= 6.0 um
4458 0 METAL7.W.2: Metal7 width must be <= 6.0 um
4462 0 METAL8.W.2: Metal8 width must be <= 6.0 um
4464 0 METAL9.W.2: Metal9 width must be <= 6.0 um
4466 0 METAL10.W.2: Metal10 width must be <= 6.0 um
4468 0 METAL11.W.2: Metal11 width must be <= 6.0 um
4470 0 METAL1.SP.1.1: Metal1 to Metal1 spacing must be >= 0.06 um
4472 0 METAL2.SP.1.1: Metal2 to Metal2 spacing must be >= 0.07 um
4474 0 METAL3.SP.1.1: Metal3 to Metal3 spacing must be >= 0.07 um
4476 0 METAL4.SP.1.1: Metal4 to Metal4 spacing must be >= 0.07 um
4478 0 METAL5.SP.1.1: Metal5 to Metal5 spacing must be >= 0.07 um
4480 0 METAL6.SP.1.1: Metal6 to Metal6 spacing must be >= 0.07 um
4482 0 METAL7.SP.1.1: Metal7 to Metal7 spacing must be >= 0.07 um
4484 0 METAL8.SP.1.1: Metal8 to Metal8 spacing must be >= 0.07 um
4486 0 METAL9.SP.1.1: Metal9 to Metal9 spacing must be >= 0.07 um
4488 0 METAL10.SP.1.1: Metal10 to Metal10 spacing must be >= 0.20 um
4490 0 METAL11.SP.1.1: Metal11 to Metal11 spacing must be >= 0.20 um
4497 0 METAL1.SP.1.2: Metal1 to Metal1 spacing must be >= 0.1 um
4504 0 METAL2.SP.1.2: Metal2 to Metal2 spacing must be >= 0.15 um
4511 0 METAL3.SP.1.2: Metal3 to Metal3 spacing must be >= 0.15 um
4518 0 METAL4.SP.1.2: Metal4 to Metal4 spacing must be >= 0.15 um
4525 0 METAL5.SP.1.2: Metal5 to Metal5 spacing must be >= 0.15 um
4532 0 METAL6.SP.1.2: Metal6 to Metal6 spacing must be >= 0.15 um
4539 0 METAL7.SP.1.2: Metal7 to Metal7 spacing must be >= 0.15 um
4546 0 METAL8.SP.1.2: Metal8 to Metal8 spacing must be >= 0.15 um
4553 0 METAL9.SP.1.2: Metal9 to Metal9 spacing must be >= 0.15 um
4559 0 METAL1.SP.1.3: Metal1 to Metal1 spacing must be >= 0.25 um
4565 0 METAL2.SP.1.3: Metal2 to Metal2 spacing must be >= 0.25 um
4571 0 METAL3.SP.1.3: Metal3 to Metal3 spacing must be >= 0.25 um
4577 0 METAL4.SP.1.3: Metal4 to Metal4 spacing must be >= 0.25 um
4583 0 METAL5.SP.1.3: Metal5 to Metal5 spacing must be >= 0.25 um
4589 0 METAL6.SP.1.3: Metal6 to Metal6 spacing must be >= 0.25 um
4595 0 METAL7.SP.1.3: Metal7 to Metal7 spacing must be >= 0.25 um
4601 0 METAL8.SP.1.3: Metal8 to Metal8 spacing must be >= 0.25 um
4607 0 METAL9.SP.1.3: Metal9 to Metal9 spacing must be >= 0.25 um
4614 0 METAL10.SP.1.2: Metal10 to Metal10 spacing must be >= 0.35 um
4621 0 METAL11.SP.1.2: Metal11 to Metal11 spacing must be >= 0.35 um
4627 0 METAL1.SP.1.4: Metal1 to Metal1 spacing must be >= 0.45 um
4633 0 METAL2.SP.1.4: Metal2 to Metal2 spacing must be >= 0.45 um
4639 0 METAL3.SP.1.4: Metal3 to Metal3 spacing must be >= 0.45 um
4645 0 METAL4.SP.1.4: Metal4 to Metal4 spacing must be >= 0.45 um
4651 0 METAL5.SP.1.4: Metal5 to Metal5 spacing must be >= 0.45 um
4657 0 METAL6.SP.1.4: Metal6 to Metal6 spacing must be >= 0.45 um
4663 0 METAL7.SP.1.4: Metal7 to Metal7 spacing must be >= 0.45 um
4669 0 METAL8.SP.1.4: Metal8 to Metal8 spacing must be >= 0.45 um
4675 0 METAL9.SP.1.4: Metal9 to Metal9 spacing must be >= 0.45 um
4681 0 METAL10.SP.1.3: Metal10 to Metal10 spacing must be >= 0.45 um
4687 0 METAL11.SP.1.3: Metal11 to Metal11 spacing must be >= 0.45 um
4693 0 METAL1.SP.1.5: Metal1 to Metal1 spacing must be >= 0.75 um
4699 0 METAL2.SP.1.5: Metal2 to Metal2 spacing must be >= 0.75 um
4705 0 METAL3.SP.1.5: Metal3 to Metal3 spacing must be >= 0.75 um
4711 0 METAL4.SP.1.5: Metal4 to Metal4 spacing must be >= 0.75 um
4717 0 METAL5.SP.1.5: Metal5 to Metal5 spacing must be >= 0.75 um
4723 0 METAL6.SP.1.5: Metal6 to Metal6 spacing must be >= 0.75 um
4729 0 METAL7.SP.1.5: Metal7 to Metal7 spacing must be >= 0.75 um
4735 0 METAL8.SP.1.5: Metal8 to Metal8 spacing must be >= 0.75 um
4741 0 METAL9.SP.1.5: Metal9 to Metal9 spacing must be >= 0.75 um
4747 0 METAL10.SP.1.4: Metal10 to Metal10 spacing must be >= 0.75 um
4753 0 METAL11.SP.1.4: Metal11 to Metal11 spacing must be >= 0.75 um
4757 0 METAL1.SP.1.6: Metal1 to Metal1 spacing must be >= 1.25 um
4761 0 METAL2.SP.1.6: Metal2 to Metal2 spacing must be >= 1.25 um
4765 0 METAL3.SP.1.6: Metal3 to Metal3 spacing must be >= 1.25 um
4769 0 METAL4.SP.1.6: Metal4 to Metal4 spacing must be >= 1.25 um
4773 0 METAL5.SP.1.6: Metal5 to Metal5 spacing must be >= 1.25 um
4777 0 METAL6.SP.1.6: Metal6 to Metal6 spacing must be >= 1.25 um
4781 0 METAL7.SP.1.6: Metal7 to Metal7 spacing must be >= 1.25 um
4785 0 METAL8.SP.1.6: Metal8 to Metal8 spacing must be >= 1.25 um
4789 0 METAL9.SP.1.6: Metal9 to Metal9 spacing must be >= 1.25 um
4793 0 METAL10.SP.1.5: Metal10 to Metal10 spacing must be >= 1.25 um
4797 0 METAL11.SP.1.5: Metal11 to Metal11 spacing must be >= 1.25 um
4799 0 METAL1.L.1: Metal1 non-90 degree segments must be >= 0.1 um
4801 0 METAL2.L.1: Metal2 non-90 degree segments must be >= 0.1 um
4803 0 METAL3.L.1: Metal3 non-90 degree segments must be >= 0.1 um
4805 0 METAL4.L.1: Metal4 non-90 degree segments must be >= 0.1 um
4807 0 METAL5.L.1: Metal5 non-90 degree segments must be >= 0.1 um
4809 0 METAL6.L.1: Metal6 non-90 degree segments must be >= 0.1 um
4811 0 METAL7.L.1: Metal7 non-90 degree segments must be >= 0.1 um
4813 0 METAL8.L.1: Metal8 non-90 degree segments must be >= 0.1 um
4815 0 METAL9.L.1: Metal9 non-90 degree segments must be >= 0.1 um
4816 0 METAL1.SP.2: Metal1 to bent Metal1 spacing must be >= 0.1 um
4817 0 METAL1.W.3: Bent Metal1 (45 degree angle) width must be >= 0.07
4818 0 METAL2.SP.2: Metal2 to bent Metal2 spacing must be >= 0.1 um
4819 0 METAL2.W.3: Bent Metal2 (45 degree angle) width must be >= 0.09
4820 0 METAL3.SP.2: Metal3 to bent Metal3 spacing must be >= 0.1 um
4821 0 METAL3.W.3: Bent Metal3 (45 degree angle) width must be >= 0.09
4822 0 METAL4.SP.2: Metal4 to bent Metal4 spacing must be >= 0.1 um
4823 0 METAL4.W.3: Bent Metal4 (45 degree angle) width must be >= 0.09
4824 0 METAL5.SP.2: Metal5 to bent Metal5 spacing must be >= 0.1 um
4825 0 METAL5.W.3: Bent Metal5 (45 degree angle) width must be >= 0.09
4826 0 METAL6.SP.2: Metal6 to bent Metal6 spacing must be >= 0.1 um
4827 0 METAL6.W.3: Bent Metal6 (45 degree angle) width must be >= 0.09
4828 0 METAL7.SP.2: Metal7 to bent Metal7 spacing must be >= 0.1 um
4829 0 METAL7.W.3: Bent Metal7 (45 degree angle) width must be >= 0.09
4830 0 METAL8.SP.2: Metal8 to bent Metal8 spacing must be >= 0.1 um
4831 0 METAL8.W.3: Bent Metal8 (45 degree angle) width must be >= 0.09
4832 0 METAL9.SP.2: Metal9 to bent Metal9 spacing must be >= 0.1 um
4833 0 METAL9.W.3: Bent Metal9 (45 degree angle) width must be >= 0.09
4834 0 METAL1.SP.3: Min End of Line Spacing >= 0.08
4835 0 METAL2.SP.3: Min End of Line Spacing >= 0.08
4836 0 METAL3.SP.3: Min End of Line Spacing >= 0.08
4837 0 METAL4.SP.3: Min End of Line Spacing >= 0.08
4838 0 METAL5.SP.3: Min End of Line Spacing >= 0.08
4839 0 METAL6.SP.3: Min End of Line Spacing >= 0.08
4840 0 METAL7.SP.3: Min End of Line Spacing >= 0.08
4841 0 METAL8.SP.3: Min End of Line Spacing >= 0.08
4842 0 METAL9.SP.3: Min End of Line Spacing >= 0.08
4843 0 METAL1.A.1: Metal1 area must be >= 0.02 um
4844 0 METAL2.A.1: Metal2 area must be >= 0.02 um
4845 0 METAL3.A.1: Metal3 area must be >= 0.02 um
4846 0 METAL4.A.1: Metal4 area must be >= 0.02 um
4847 0 METAL5.A.1: Metal5 area must be >= 0.02 um
4848 0 METAL6.A.1: Metal6 area must be >= 0.02 um
4849 0 METAL7.A.1: Metal7 area must be >= 0.02 um
4850 0 METAL8.A.1: Metal8 area must be >= 0.02 um
4851 0 METAL9.A.1: Metal9 area must be >= 0.02 um
4852 0 METAL10.A.1: Metal10 area must be >= 0.10 um
4853 0 METAL11.A.1: Metal11 area must be >= 0.10 um
4857 0 METAL1.EA.1: Metal1 enclosed area must be >= 0.05 um
4861 0 METAL2.EA.1: Metal2 enclosed area must be >= 0.05 um
4865 0 METAL3.EA.1: Metal3 enclosed area must be >= 0.05 um
4869 0 METAL4.EA.1: Metal4 enclosed area must be >= 0.05 um
4873 0 METAL5.EA.1: Metal5 enclosed area must be >= 0.05 um
4877 0 METAL6.EA.1: Metal6 enclosed area must be >= 0.05 um
4881 0 METAL7.EA.1: Metal7 enclosed area must be >= 0.05 um
4885 0 METAL8.EA.1: Metal8 enclosed area must be >= 0.05 um
4889 0 METAL9.EA.1: Metal9 enclosed area must be >= 0.05 um
4893 0 METAL10.EA.1: Metal10 enclosed area must be >= 0.05 um
4897 0 METAL11.EA.1: Metal11 enclosed area must be >= 0.05 um
4899 0 CMET.S.1: Minimum space of CapMetal >= 1.0 um
4900 0 CMET.W.1: Minimum width of CapMetal >= 1.0 um
4902 0 CMET.E.1: Minimum Metal 1 overlap of Via 10 on CapMetal >= 0.05 um
4904 0 CMET.E.1: Minimum Metal 1 overlap of Via 10 on CapMetal >= 0.05 um
4906 0 CMET.E.2: Minimum CapMetal overlap of Via 10 >= 0.15 um
4908 0 CMET.E.2: Minimum CapMetal overlap of Via 10 >= 0.15 um
4910 0 CMET.E.4: Minimum Metal 10 overlap of CapMetal >= 0.2 um
4912 0 CMET.E.4: Minimum Metal 10 overlap of CapMetal >= 0.2 um
4914 0 CMET.E.3: Minimum CapMetal extension over Metal 11 >= 0.1 um
4916 0 VIA1.W.1: Via1 shapes must be 0.07x0.07 rectangles
4918 0 VIA1.SP.1: Via1 to Via1 spacing must be >= 0.07 um
4920 0 VIA2.W.1: Via2 shapes must be 0.07x0.07 rectangles
4922 0 VIA2.SP.1: Via2 to Via2 spacing must be >= 0.07 um
4924 0 VIA3.W.1: Via3 shapes must be 0.07x0.07 rectangles
4926 0 VIA3.SP.1: Via3 to Via3 spacing must be >= 0.07 um
4928 0 VIA4.W.1: Via4 shapes must be 0.07x0.07 rectangles
4930 0 VIA4.SP.1: Via4 to Via4 spacing must be >= 0.07 um
4932 0 VIA5.W.1: Via5 shapes must be 0.07x0.07 rectangles
4934 0 VIA5.SP.1: Via5 to Via5 spacing must be >= 0.07 um
4936 0 VIA6.W.1: Via6 shapes must be 0.07x0.07 rectangles
4938 0 VIA6.SP.1: Via6 to Via6 spacing must be >= 0.07 um
4940 0 VIA7.W.1: Via7 shapes must be 0.07x0.07 rectangles
4942 0 VIA7.SP.1: Via7 to Via7 spacing must be >= 0.07 um
4944 0 VIA8.W.1: Via8 shapes must be 0.07x0.07 rectangles
4946 0 VIA8.SP.1: Via8 to Via8 spacing must be >= 0.07 um
4948 0 VIA9.W.1: Via9 shapes must be 0.18x0.18 rectangles
4950 0 VIA9.SP.1: Via9 to Via9 spacing must be >= 0.18 um
4952 0 VIA10.W.1: Via10 shapes must be 0.18x0.18 rectangles
4954 0 VIA10.SP.1: Via10 to Via10 spacing must be >= 0.18 um
4955 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
4957 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
4961 0 VIA1.E.2: Metal1 to Via1 enclosure on opposite sides must be >= 0.03 um
4962 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
4964 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
4968 0 VIA2.E.2: Metal2 to Via2 enclosure on opposite sides must be >= 0.03 um
4969 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
4971 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
4975 0 VIA3.E.2: Metal3 to Via3 enclosure on opposite sides must be >= 0.03 um
4976 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
4978 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
4982 0 VIA4.E.2: Metal4 to Via4 enclosure on opposite sides must be >= 0.03 um
4983 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
4985 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
4989 0 VIA5.E.2: Metal5 to Via5 enclosure on opposite sides must be >= 0.03 um
4990 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
4992 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
4996 0 VIA6.E.2: Metal6 to Via6 enclosure on opposite sides must be >= 0.03 um
4997 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.005 um
4999 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.005 um
5003 0 VIA7.E.2: Metal7 to Via7 enclosure on opposite sides must be >= 0.03 um
5004 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.005 um
5006 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.005 um
5010 0 VIA8.E.2: Metal8 to Via8 enclosure on opposite sides must be >= 0.03 um
5011 0 VIA9.E.1: Metal9 to Via9 enclosure must be >= 0.015 um
5013 0 VIA9.E.1: Metal9 to Via9 enclosure must be >= 0.015 um
5017 0 VIA9.E.2: Metal9 to Via9 enclosure on opposite sides must be >= 0.04 um
5018 0 VIA10.E.1: Metal10 to Via10 enclosure must be >= 0.015 um
5020 0 VIA10.E.1: Metal10 to Via10 enclosure must be >= 0.015 um
5024 0 VIA10.E.2: Metal10 to Via10 enclosure on opposite sides must be >= 0.04 um
5241 0 LATCHUP.1: The maximum distance from any point in a P+ source/drain Active Area to the nearest Nwell pick-up in the same Nwell >= 20.0 um
5840 0 LATCHUP.2: The maximum distance from any point in a N+ source/drain Active Area to the nearest Psub pick-up in the same Psub >= 20.0 um
5843 0 LATCHUP.3: Minimum I/O or ESD NMOS to PMOS spacing >= 10.0 um
5844 0 LATCHUP.3: Minimum I/O or ESD NMOS to PMOS spacing >= 10.0 um
5849 0 LATCHUP.4: Minimum I/O or ESD NMOS to PMOS spacing when not blocked by a double guardring >= 30.0 um
5853 0 LATCHUP.4: Minimum I/O or ESD NMOS to PMOS spacing when not blocked by a double guardring >= 30.0 um
5857 0 ESD.1: ESD gate width must be >= 10.0 um and <= 30.0 um
5858 0 ESD.4: N+ source should connect to Pad or Bulk
5859 0 ESD.4: P+ source should connect to Pad or Nwell
5860 0 ESD.5: NMOS I/O and ESD devices must be inside P+ rings
5861 0 ESD.6: PMOS I/O and ESD devices must be inside N+ rings
5862 0 ESD.7: P+ taps can NOT butt NMOS I/O and ESD devices
5863 0 ESD.7: N+ taps can NOT butt PMOS I/O and ESD devices
5864 0 ESD.8: N+ drains must be non-salicided (except Contact area)
5865 0 ESD.8: P+ drains must be non-salicided (except Contact area)
5868 0 ESD.11: Minimum SiProt to Poly gate overlap in NMOS and PMOS drains >= 0.05 um
5870 0 ESD.12: Minimum enclosure of SiProt edge to Poly gate edge in NMOS and PMOS drains >= 0.9 um
5872 0 ESD.13: Minimum SiProt to Oxide overlap in NMOS and PMOS I/O drains >= 0.9 um
5876 0 ESD.14: Exact gate length of NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection == 0.2 um
5880 0 ESD.15: Minimu Poly gate to Contact spacing in NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection >= 0.12 um
5881 0 ESD.15: Minimu Poly gate to Contact spacing in NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection >= 0.12 um
5883 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
5885 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
5886 0 BONDPAD.SP.2: Bondpad Metal1 to Metal1 spacing must be >= 3.0 um
5888 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
5890 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
5891 0 BONDPAD.SP.2: Bondpad Metal2 to Metal2 spacing must be >= 3.0 um
5893 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
5895 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
5896 0 BONDPAD.SP.2: Bondpad Metal3 to Metal3 spacing must be >= 3.0 um
5898 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
5900 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
5901 0 BONDPAD.SP.2: Bondpad Metal4 to Metal4 spacing must be >= 3.0 um
5903 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
5905 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
5906 0 BONDPAD.SP.2: Bondpad Metal5 to Metal5 spacing must be >= 3.0 um
5908 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
5910 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
5911 0 BONDPAD.SP.2: Bondpad Metal6 to Metal6 spacing must be >= 3.0 um
5913 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
5915 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
5916 0 BONDPAD.SP.2: Bondpad Metal7 to Metal7 spacing must be >= 3.0 um
5918 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
5920 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
5921 0 BONDPAD.SP.2: Bondpad Metal8 to Metal8 spacing must be >= 3.0 um
5923 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
5925 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
5926 0 BONDPAD.SP.2: Bondpad Metal9 to Metal9 spacing must be >= 3.0 um
5928 0 BONDPAD.E.1: Metal10 to Bondpad enclosure must be >= 2.0 um
5930 0 BONDPAD.E.1: Metal10 to Bondpad enclosure must be >= 2.0 um
5931 0 BONDPAD.SP.2: Bondpad Metal10 to Metal10 spacing must be >= 3.0 um
5933 0 BONDPAD.E.1: Metal11 to Bondpad enclosure must be >= 2.0 um
5935 0 BONDPAD.E.1: Metal11 to Bondpad enclosure must be >= 2.0 um
5936 0 BONDPAD.SP.2: Bondpad Metal11 to Metal11 spacing must be >= 3.0 um
5939 0 BONDPAD.W.1: Bondpad width must be >= 55.0 um
5941 0 BONDPAD.W.1: Bondpad width must be >= 55.0 um
5943 0 BONDPAD.SP.1: Bondpad to Bondpad spacing must be >= 8.0 um
5945 0 BONDPAD.B.1B: Bondpad Metal1 beveled segments must be >= 1.8 um and <= 3.2 um
5947 0 BONDPAD.B.1B: Bondpad Metal2 beveled segments must be >= 1.8 um and <= 3.2 um
5949 0 BONDPAD.B.1B: Bondpad Metal3 beveled segments must be >= 1.8 um and <= 3.2 um
5951 0 BONDPAD.B.1B: Bondpad Metal4 beveled segments must be >= 1.8 um and <= 3.2 um
5953 0 BONDPAD.B.1B: Bondpad Metal5 beveled segments must be >= 1.8 um and <= 3.2 um
5955 0 BONDPAD.B.1B: Bondpad Metal6 beveled segments must be >= 1.8 um and <= 3.2 um
5957 0 BONDPAD.B.1B: Bondpad Metal7 beveled segments must be >= 1.8 um and <= 3.2 um
5959 0 BONDPAD.B.1B: Bondpad Metal8 beveled segments must be >= 1.8 um and <= 3.2 um
5961 0 BONDPAD.B.1B: Bondpad Metal9 beveled segments must be >= 1.8 um and <= 3.2 um
5963 0 BONDPAD.B.1B: Bondpad Metal10 beveled segments must be >= 1.8 um and <= 3.2 um
5965 0 BONDPAD.B.1B: Bondpad Metal11 beveled segments must be >= 1.8 um and <= 3.2 um
5968 0 BONDPAD.SP.3: Bondpad Via1 to Bondpad Via1 spacing must be >= 0.22 um
5971 0 BONDPAD.SP.3: Bondpad Via2 to Bondpad Via2 spacing must be >= 0.22 um
5974 0 BONDPAD.SP.3: Bondpad Via3 to Bondpad Via3 spacing must be >= 0.22 um
5977 0 BONDPAD.SP.3: Bondpad Via4 to Bondpad Via4 spacing must be >= 0.22 um
5980 0 BONDPAD.SP.3: Bondpad Via5 to Bondpad Via5 spacing must be >= 0.22 um
5983 0 BONDPAD.SP.3: Bondpad Via6 to Bondpad Via6 spacing must be >= 0.22 um
5986 0 BONDPAD.SP.4: Bondpad Via7 to Bondpad Via7 spacing must be >= 0.22 um
5989 0 BONDPAD.SP.4: Bondpad Via8 to Bondpad Via8 spacing must be >= 0.22 um
5992 0 BONDPAD.SP.4: Bondpad Via9 to Bondpad Via9 spacing must be >= 0.54 um
5995 0 BONDPAD.SP.4: Bondpad Via10 to Bondpad Via10 spacing must be >= 0.54 um
5997 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
5999 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
6001 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
6003 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
6005 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
6007 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
6009 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
6011 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
6013 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
6015 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
6017 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
6019 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
6021 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.05 um
6023 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.05 um
6025 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.05 um
6027 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.05 um
6029 0 BONDPAD.E.3: Bondpad Metal9 to Via9 enclosure must be >= 0.09 um
6031 0 BONDPAD.E.3: Bondpad Metal9 to Via9 enclosure must be >= 0.09 um
6033 0 BONDPAD.E.3: Bondpad Metal9 to Via10 enclosure must be >= 0.09 um
6035 0 BONDPAD.E.3: Bondpad Metal9 to Via10 enclosure must be >= 0.09 um
6037 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
6039 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
6041 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
6043 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
6045 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
6047 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
6049 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
6051 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
6053 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
6055 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
6057 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
6059 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
6061 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.05 um
6063 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.05 um
6065 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.05 um
6067 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.05 um
6069 0 BONDPAD.E.3: Bondpad Metal10 to Via9 enclosure must be >= 0.09 um
6071 0 BONDPAD.E.3: Bondpad Metal10 to Via9 enclosure must be >= 0.09 um
6073 0 BONDPAD.E.3: Bondpad Metal11 to Via10 enclosure must be >= 0.09 um
6075 0 BONDPAD.E.3: Bondpad Metal11 to Via10 enclosure must be >= 0.09 um
6076 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
6077 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
6078 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
6079 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
6080 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
6081 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
6082 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
6083 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
6084 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
6085 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
6086 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
6087 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
6088 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
6089 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
6090 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
6091 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
6092 0 BONDPAD.SP.6: Bondpad Metal9 to Bondpad Metal9 spacing across first slot must be >= 1.00 um and <= 3.50 um
6093 0 BONDPAD.SP.6: Bondpad Metal9 to Bondpad Metal9 spacing across first slot must be >= 1.00 um and <= 3.50 um
6094 0 BONDPAD.SP.6: Bondpad Metal10 to Bondpad Metal10 spacing across first slot must be >= 1.00 um and <= 3.50 um
6095 0 BONDPAD.SP.6: Bondpad Metal10 to Bondpad Metal10 spacing across first slot must be >= 1.00 um and <= 3.50 um
6097 0 BONDPAD.SP.7: Bondpad Via1 array to Bondpad Via1 array spacing must be >= 1.1 um
6099 0 BONDPAD.SP.7: Bondpad Via2 array to Bondpad Via2 array spacing must be >= 1.1 um
6101 0 BONDPAD.SP.7: Bondpad Via3 array to Bondpad Via3 array spacing must be >= 1.1 um
6103 0 BONDPAD.SP.7: Bondpad Via4 array to Bondpad Via4 array spacing must be >= 1.1 um
6105 0 BONDPAD.SP.7: Bondpad Via5 array to Bondpad Via5 array spacing must be >= 1.1 um
6107 0 BONDPAD.SP.7: Bondpad Via6 array to Bondpad Via6 array spacing must be >= 1.1 um
6109 0 BONDPAD.SP.7: Bondpad Via7 array to Bondpad Via7 array spacing must be >= 1.1 um
6111 0 BONDPAD.SP.7: Bondpad Via8 array to Bondpad Via8 array spacing must be >= 1.1 um
6113 0 BONDPAD.SP.7: Bondpad Via9 array to Bondpad Via9 array spacing must be >= 1.1 um
6115 0 BONDPAD.SP.7: Bondpad Via10 array to Bondpad Via10 array spacing must be >= 1.1 um
6118 0 OXIDER.W.1.1: Minimum Active Resistor width >= 0.1 um
6121 0 POLYR.W.1.1: Minimum Poly resistor width >= 0.1 um
